/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Flashcard, TopicNote, Badge } from './types';

export const FLASHCARDS: Flashcard[] = [
  {
    id: "fc-1",
    category: "Electrostatics",
    front: "What is Coulomb's Law and how is the electrostatic force related to distance?",
    back: "Coulomb's Law states that the electrostatic force between two point charges is directly proportional to the product of their charges and inversely proportional to the square of the distance between them (F = k * q1 * q2 / r²)."
  },
  {
    id: "fc-2",
    category: "Current Electricity",
    front: "State Ohm's Law and define resistance.",
    back: "Ohm's Law states that the current (I) flowing through a conductor is directly proportional to the potential difference (V) across it, provided temperature and other physical conditions remain constant (V = IR). Resistance (R) is the opposition to current flow."
  },
  {
    id: "fc-3",
    category: "Magnetism",
    front: "What is Lenz's Law and what physical principle does it represent?",
    back: "Lenz's Law states that the direction of an induced current is such that its magnetic field opposes the change in magnetic flux that created it. It represents the Conservation of Energy."
  },
  {
    id: "fc-6",
    category: "Electrostatics",
    front: "What is the physical meaning of Gauss's Law?",
    back: "The total electric flux through any closed Gaussian surface is equal to the net charge enclosed by the surface divided by the permittivity of free space (Φ = Q_enclosed / ε0)."
  }
];

export const TOPIC_NOTES: TopicNote[] = [
  {
    id: "note-1",
    title: "1. Electrostatics",
    content: "Electrostatics is the study of stationary electric charges. Core concepts include Coulomb's Law for point charges, electric fields as force per unit charge, Gauss's Law for electric flux, electric potential as work done per unit charge, and capacitance as a measure of stored charge per unit potential.",
    keyPoints: [
      "The electric field inside a conductor in electrostatic equilibrium is always zero, and excess charge resides entirely on its surface.",
      "The capacitance of a parallel-plate capacitor is given by C = K * ε0 * A / d, where K is the dielectric constant of the material.",
      "Electric field lines are always perpendicular to equipotential surfaces, running from higher potential to lower potential."
    ]
  },
  {
    id: "note-2",
    title: "2. Current Electricity & DC Circuits",
    content: "Current electricity focuses on moving electric charges. Key principles involve current as rate of charge flow, resistance and resistivity, Ohm's law, electric power dissipation, and Kirchhoff's loop and junction rules for circuit analysis.",
    keyPoints: [
      "Kirchhoff's Junction Rule is based on the Conservation of Charge; the Loop Rule is based on the Conservation of Energy.",
      "When a wire is stretched to n times its length, its area decreases by 1/n, making its new resistance n² times the original resistance.",
      "The equivalent resistance of parallel resistors is always less than any individual resistor in the parallel combination."
    ]
  },
  {
    id: "note-3",
    title: "3. Magnetism & Electromagnetism",
    content: "Magnetism explores magnetic fields generated by moving charges or currents. Topics include magnetic force on charges and wires, Biot-Savart and Ampere's laws, Faraday's law of induction, and alternating currents (AC) with transformers.",
    keyPoints: [
      "The magnetic force on a moving charge is F = q(v × B); it does zero work on the charge because the force is always perpendicular to velocity.",
      "Two parallel wires carrying currents in the same direction attract each other; wires carrying opposite currents repel.",
      "Faraday's Law of Induction states that the induced electromotive force in a circuit is proportional to the rate of change of magnetic flux."
    ]
  }
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: "badge-1",
    title: "Phy Beginner",
    description: "Complete your first practice quiz on PHY 102 Master.",
    unlocked: false,
    iconName: "Compass"
  },
  {
    id: "badge-2",
    title: "Electrostatics Expert",
    description: "Get 100% correct in any quiz focusing on Electrostatics.",
    unlocked: false,
    iconName: "Zap"
  },
  {
    id: "badge-3",
    title: "Magnetism Master",
    description: "Score perfectly on Magnetism & Electromagnetism questions.",
    unlocked: false,
    iconName: "FileCheck"
  },
  {
    id: "badge-5",
    title: "100% Club",
    description: "Achieve a perfect 100% score on a full 20+ question practice exam.",
    unlocked: false,
    iconName: "Award"
  },
  {
    id: "badge-6",
    title: "Streak Master",
    description: "Reach a study streak of 3 consecutive days.",
    unlocked: false,
    iconName: "Flame"
  },
  {
    id: "badge-7",
    title: "Fast Finisher",
    description: "Complete an exam or custom quiz with more than 50% of the timer remaining.",
    unlocked: false,
    iconName: "Timer"
  }
];
